neovim: map F1 to makeprog
profile: change polaris environment variables

gnupg: increase cache time to last the entire user session

bin: add lsgh script for enumerating a user's github repos

pre-commit: add gitleaks pre-commit hook

diff --git a/bin/update-repos/.local/bin/update-repos b/bin/update-repos/.local/bin/update-repos
--- a/bin/update-repos/.local/bin/update-repos
+++ b/bin/update-repos/.local/bin/update-repos
@@ -88,8 +88,10 @@ update() {
 			# Redirection order is intentional: suppress git errors and redirect stdout to stderr
 			# shellcheck disable=SC2069
 			if ! git -C "$1" -c color.ui=always pull --ff-only 2>&1 2>/dev/null; then
-				printf "${RED}\t\t==> ERROR: %s${NOFORMAT}\n" "${1##*/}" >&2
+				printf "${RED}╚═[ERROR]: %s${NOFORMAT}\n" "${1##*/}" >&2
 			fi
+		else
+			printf "${BLUE}╚═[INFO]: No remote configured for %s${NOFORMAT}\n" "${1##*/}" >&2
 		fi
 	}
 	export -f git_pull
